[project]
name = "f3dmaojoco"
version = "0.1.0"
description = "Fusion 360 到 MuJoCo 的机器人模型转换与仿真控制工具链"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "brax>=0.14.2",
    "gymnasium>=1.3.0",
    "jax>=0.6.0",
    "jaxlib>=0.6.0",
    "mujoco>=3.3.5",
    "mujoco-mjx>=3.10.0",
    "networkx>=3.5",
    "pypinyin>=0.55.0",
    "pyside6>=6.9.2",
    "pyvista>=0.46.3",
    "stable-baselines3>=2.9.0",
    "torch>=2.13.0",
]

[dependency-groups]
dev = [
    "scipy>=1.18.0",
]
